---
- name: Enable Powershell remoting via Azure Extensions
  hosts: localhost
  tasks:
    - name: EnablePowerShellRemoting via Azure VM Extension
      azure_rm_virtualmachine_extension:
        name: EnableAnsibleWinRM3
        resource_group: CTFRG
        virtual_machine_name: ctfwrkbase
        publisher: Microsoft.Compute
        virtual_machine_extension_type: CustomScriptExtension
        type_handler_version: 1.8
        settings: '{"fileUris": [ "https://raw.githubusercontent.com/ansible/ansible/devel/examples/scripts/ConfigureRemotingForAnsible.ps1" ]}'
        protected_settings: '{"commandToExecute": "powershell -ExecutionPolicy Unrestricted -File ConfigureRemotingForAnsible.ps1 -EnableCredSSP"}'
        auto_upgrade_minor_version: true

