- name: Azure CTF Infrastructure playbook
  hosts: localhost
  vars:
    rgname: "CTFRG"
    region: "eastus"
    workstationuser: "ctfuser"
    workstationnsg: "ctf-workstation-nsg"
    workstationsubnet: "ctf-wrk-subnet"
    workstationnic: "ctf-wrk-nic"
    workstationdnslabel: "ctfwrk"
    workstationcount: 2
    vnetname: "CTF-VNET1"
  vars_files:
    - secrets.yml
      # We fetch remoteallowedip and workstationpass from here

  tasks:
    # We could literally iterate this for the number of workstations we need
    # If I can work out the automation on windows.
    - name: create workstation Public IP
      azure_rm_publicipaddress:
        resource_group: "{{ rgname }}"
        name: "workstationpip{{ item }}"
        domain_name_label: "{{ workstationdnslabel }}{{ item }}"
      with_sequence: start=1 end={{ workstationcount }}

    - name: Create base workstation NIC
      azure_rm_networkinterface:
        resource_group: "{{ rgname }}"
        name: "{{ workstationnic }}{{ item }}"
        public_ip_address_name: "workstationpip{{ item }}"
        virtual_network_name: "{{ vnetname }}"
        subnet_name: "{{ workstationsubnet }}"
        security_group_name: "{{ workstationnsg }}"
      with_sequence: start=1 end={{ workstationcount }}

    - name: Create workstation base image
      azure_rm_virtualmachine:
        resource_group: "{{ rgname }}"
        name: ctfwrkbase
        vm_size: Standard_D2_v3
        managed_disk_type: Standard_LRS
        admin_username: "{{ workstationuser }}"
        admin_password: "{{ workstationpass }}"
        network_interface_names: "{{ workstationnic }}"
        os_type: Windows
        image:
          name: ctfwrkbase-image-20180715162400
          resource_group: "{{ rgname }}"
      with_sequence: start=1 end={{ workstationcount }}

